shiny::runApp('~/Documents/shiny/app1')
shiny::runApp('~/Documents/shiny/app2')
shiny::runApp('~/Documents/shiny/app3')
shiny::runApp('~/Documents/shiny/app4')
shiny::runApp('~/Documents/shiny/app5')
shiny::runApp('~/Documents/shiny/app6')
shiny::runApp('~/Documents/shiny/app6b')
shiny::runApp('~/Documents/shiny/app6c')
shiny::runApp('~/Documents/shiny/app7')
shiny::runApp('~/Documents/shiny/app7b')
shiny::runApp('~/Documents/shiny/app8')
shiny::runApp('~/Documents/shiny/app9')
shiny::runApp('~/Documents/shiny/app10')
shiny::runApp('~/Documents/shiny/app11')
shiny::runApp('~/Documents/shiny/app12')
shiny::runApp('~/Documents/shiny/app12a')
shiny::runApp('~/Documents/shiny/app13')
shiny::runApp('~/Documents/shiny/app14')
shiny::runApp('~/Documents/shiny/app15')
shiny::runApp('~/Documents/shiny/app16')
shiny::runApp('~/Documents/shiny/lab2')
shiny::runApp('~/Documents/shiny/lab4')
shiny::runApp('~/Documents/shiny/lab5')


